services:
  app:
    container_name: app
    image: assessment:latest
    ports:
      - 8080:8080
    volumes:
      - demo-data:/var/lib/mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/demo?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    restart: always

  db:
    container_name: database
    image: mysql:latest
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
    restart: always

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiYzJmNjEzYTNjMjAwNTMyM2E5MzNjOTBlYThhYWMzMWUiLCJ0IjoiNmU2ZWU4OGMtZmNiOS00OTU4LWI2YzQtMTg4OTUyM2Q1ZmUzIiwicyI6Ik1UUTFZVGczTlRJdE9UQTFaQzAwTkdNM0xXRTFPR1V0TW1VMU16UTFNRE5qWWpabSJ9 # Replace with your own token
    restart: always

volumes:
  demo-data: